/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5550681d-1ac9-415d-99af-c57eab1971e8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5GvAzSWkt",
    "aws_user_pools_web_client_id": "61j01n3tm24cuipkunt9k6sj4t",
    "oauth": {}
};


export default awsmobile;
